vim.g.mapleader = " "
local keymap = vim.keymap
keymap.set("i", "jk", "<ESC>")
keymap.set("n", "<leader>sr", "<C-w>v")
keymap.set("n", "<leader>sw", "<C-w>s")
keymap.set("n", "<leader>ch", ":nohl<CR>")
keymap.set("n", "<leader>e", ":NvimTreeToggle<CR>")
keymap.set("n", "<c-m-l>", ":lua vim.lsp.buf.format()<cr>")
keymap.set("n", "<leader>gd", ":Lspsaga goto_definition<cr>")
keymap.set("n", "<leader>gt", ":Lspsaga goto_type_definition<cr>")
keymap.set("n", "<leader>gf", ":Lspsaga code_action<cr>")
keymap.set("n", "<leader>gg", ":LazyGit<cr>")
keymap.set("n", "<leader>gn", ":Lspsaga diagnostic_jump_next<cr>")
keymap.set("n", "<leader>gp", ":Lspsaga diagnostic_jump_prev<cr>")
keymap.set("n", "<leader>t", ":Lspsaga term_toggle<cr>")
keymap.set("n", "<m-/>", ":CommentToggle<cr>")
keymap.set("n", "<leader>b", ":FlyBuf<cr>")
keymap.set("n", "<leader>n", ":TablineBufferNext<cr>")
keymap.set("n", "<leader>p", ":TablineBufferPrevious<cr>")
keymap.set("n", "<leader>db", ":lua require'dap'.toggle_breakpoint()<cr>")
keymap.set("n", "<f5>", ":lua require'dap'.continue()<cr>")
keymap.set("n", "<f6>", ":lua require'dap'.step_over()<cr>")
keymap.set("n", "<f7>", ":lua require'dap'.step_into()<cr>")
keymap.set("n", "<f8>", ":lua require'dap'.step_out()<cr>")
